-----------------------CREATE TABLE
CREATE TABLE TBL_MEMBER (
    MEMBER_ID          BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '회원 PK',
    MEMBER_NAME        VARCHAR(50)  NOT NULL COMMENT '회원 이름',
    MEMBER_EMAIL       VARCHAR(100) COMMENT '회원 이메일 (선택)',
    MEMBER_LOGIN_ID    VARCHAR(100) NOT NULL UNIQUE COMMENT '로그인 ID (Local: ID, Kakao: 고유번호)',
    MEMBER_PASSWORD    VARCHAR(255) NOT NULL COMMENT '암호화된 비밀번호',
    MEMBER_REGION      VARCHAR(100) NOT NULL COMMENT '회원 주소/지역',
    MEMBER_BIRTH        DATE         NOT NULL COMMENT '생년월일 (LocalDate 매핑)',
    MEMBER_ROLE        VARCHAR(20)  NOT NULL DEFAULT 'ROLE_USER' COMMENT '권한 (ROLE_USER, ROLE_ADMIN)',
    MEMBER_GENDER      VARCHAR(10)  COMMENT '성별',
    MEMBER_PHONE       VARCHAR(20)  COMMENT '전화번호 (선택)',
    MEMBER_PROVIDER    VARCHAR(20)  NOT NULL DEFAULT 'LOCAL' COMMENT '로그인 방식 (local, kakao)',
    MEMBER_CREATED_AT  DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT '가입일자'
);

CREATE TABLE TBL_POLICY (
    POLICY_ID                    BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '정책 PK',
    POLICY_SOURCE                VARCHAR(50) NOT NULL COMMENT '정책 데이터 출처',
    POLICY_EXTERNAL_ID           VARCHAR(50) NOT NULL COMMENT '외부 정책 고유번호',
    POLICY_NAME                  VARCHAR(255) NOT NULL COMMENT '정책명',
    POLICY_DESCRIPTION           TEXT COMMENT '정책 설명',
    POLICY_KEYWORDS              VARCHAR(500) COMMENT '정책 키워드',
    POLICY_LARGE_CATEGORY        VARCHAR(100) COMMENT '정책 대분류',
    POLICY_MEDIUM_CATEGORY       VARCHAR(100) COMMENT '정책 중분류',
    POLICY_SUPPORT_CONTENT       TEXT COMMENT '정책 지원 내용',
    POLICY_ORGANIZATION_NAME     VARCHAR(255) COMMENT '주관 기관명',
    POLICY_APPLICATION_METHOD    TEXT COMMENT '정책 신청 방법',
    POLICY_APPLICATION_URL       VARCHAR(1000) COMMENT '정책 신청 URL',
    POLICY_SUBMISSION_DOCUMENTS  TEXT COMMENT '제출 서류',
    POLICY_REFERENCE_URL         VARCHAR(1000) COMMENT '참고 URL',
    POLICY_MIN_AGE               INT COMMENT '지원 최소 나이',
    POLICY_MAX_AGE               INT COMMENT '지원 최대 나이',
    POLICY_ADDITIONAL_CONDITION  TEXT COMMENT '추가 신청 자격조건',
    POLICY_REGION_CODES          TEXT COMMENT '지원 지역 코드 목록',
    POLICY_STATUS                VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '정책 상태',
    POLICY_CREATED_AT            DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '정책 DB 등록일',
    POLICY_UPDATED_AT            DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '정책 DB 수정일',

    CONSTRAINT UK_POLICY_SOURCE_EXTERNAL
        UNIQUE (
                POLICY_SOURCE,
                POLICY_EXTERNAL_ID
            )
);

-----------------------SELECT TABLE
SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_POLICY;
-----------------------DROP TABLE
DROP TABLE TBL_MEMBER;
DROP TABLE TBL_POLICY;








-------------------------DROP TABLE
DROP TABLE TBL_MEMBER;







