CREATE TABLE TBL_MEMBER (
    MEMBER_ID          BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '회원 PK',
    MEMBER_NAME        VARCHAR(50)  NOT NULL COMMENT '회원 이름',
    MEMBER_EMAIL       VARCHAR(100) COMMENT '회원 이메일 (선택)',
    MEMBER_LOGIN_ID    VARCHAR(100) NOT NULL UNIQUE COMMENT '로그인 ID (Local: ID, Kakao: 고유번호)',
    MEMBER_PASSWORD    VARCHAR(255) NOT NULL COMMENT '암호화된 비밀번호',
    MEMBER_REGION      VARCHAR(100) NOT NULL COMMENT '회원 주소/지역',
    MEMBER_BIRTH        DATE         NOT NULL COMMENT '생년월일 (LocalDate 매핑)',
    MEMBER_ROLE        VARCHAR(20)  NOT NULL DEFAULT 'ROLE_USER' COMMENT '권한 (ROLE_USER, ROLE_ADMIN)',
    MEMBER_GENDER      VARCHAR(10)  COMMENT '성별',
    MEMBER_PHONE       VARCHAR(20)  COMMENT '전화번호 (선택)',
    MEMBER_PROVIDER    VARCHAR(20)  NOT NULL DEFAULT 'LOCAL' COMMENT '로그인 방식 (LOCAL, KAKAO)',
    MEMBER_CREATED_AT  DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT '가입일자'
);

-----------------------SELECT TABLE
SELECT * FROM TBL_MEMBER;
-----------------------DROP TABLE
DROP TABLE TBL_MEMBER;








-------------------------DROP TABLE
DROP TABLE TBL_MEMBER;







